#!/bin/bash
set -e

TEST_DATABASE="${POSTGRES_DATABASE}_test"

psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" <<-EOSQL
  CREATE DATABASE ${POSTGRES_DATABASE};
  CREATE DATABASE ${TEST_DATABASE};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DATABASE} TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${TEST_DATABASE} TO ${POSTGRES_USER};
EOSQL
